############################################################
#
# Automation Buttons
#
############################################################

############################################################
#
# Bed Room Button - Turn Trent Bedside Lamp on
#
############################################################

- alias: Bed Room Button - Bedside Lamp toggle
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21086
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.trent_bedside

############################################################
#
# Bed Room Button - Good Night
#
############################################################

- alias: Bed Room Button - Good Night
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21086
      click_type: hold
  action:
  - service: script.good_night

############################################################
#
# Bed Room Button - Turn Rachel Bedside Lamp on
#
############################################################

- alias: Bed Room Button - Rachel Bedside Lamp toggle
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000186e632
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.rachel_bedside

############################################################
#
# Entryway Button Right - Toggle Entry Light.
#
############################################################

- alias: Entryway Button Right - Toggle Entry Light
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d000170ef78
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.entry

############################################################
#
# Entryway Button Left - Toggle Entryway Light.
#
############################################################

- alias: Entryway Button Left - Toggle Entryway Light
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d000170ef78
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.entryway
