############################################################
#
# Automation ifttt
#
############################################################

############################################################
#
# Bed Room Button - Turn Trent Bedside Lamp on
#
############################################################

- alias: Bed Room Button - Bedside Lamp toggle
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21086
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.trent_bedside

############################################################
#
# Bed Room Button - Good Night
#
############################################################

- alias: Bed Room Button - Good Night
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21086
      click_type: hold
  action:
  - service: script.good_night
