############################################################
#
# Home Assistant Media Player Dimmer Automation
#
############################################################

############################################################
#
# Home Assistant Living Room TV - Playing
#
############################################################

- alias: "Living Room TV - Playing"
  trigger:
  - platform: state
    entity_id: media_player.tv_ua55ju6400
    to: 'playing'
  condition:
    condition: and
    conditions:
#    - condition: sun
#      after: sunset
    - condition: state
      entity_id: input_boolean.mediaplayer_dimmer_livingroom
      state: 'on'
    - condition: state
      entity_id: light.living_room
      state: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.living_room
      brightness_pct: '{{ states.input_number.mediaplayer_dimmer_livingroom.state | int }}'
      transition: '2'
############################################################
#
# Home Assistant Living Room TV  - Paused
#
############################################################      
      
- alias: "Living Room TV - Paused"
  trigger:
  - platform: state
    entity_id: media_player.tv_ua55ju6400
    to: 'paused'
  condition:
    condition: and
    conditions:
#    - condition: sun
#      after: sunset
    - condition: state
      entity_id: input_boolean.mediaplayer_dimmer_livingroom
      state: 'on'
    - condition: state
      entity_id: light.living_room
      state: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.living_room
      brightness_pct: '100'
      transition: '2'
############################################################
#
# Home Assistant Living Room TV / Living Room Chrome Cast - Stopped
#
############################################################  

- alias: "Living Room TV - Stopped"
  trigger:
  - platform: state
    entity_id: media_player.tv_ua55ju6400
    from: 'playing'
    to: 'idle'
  - platform: state
    entity_id: media_player.tv_ua55ju6400
    from: 'paused'
    to: 'idle'
  condition:
    condition: and
    conditions:
#    - condition: sun
#      after: sunset
    - condition: state
      entity_id: input_boolean.mediaplayer_dimmer_livingroom
      state: 'on'
    - condition: state
      entity_id: light.living_room
      state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.living_room_light_full