homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
 
# Customizations
  customize: !include includes/customize.yaml
  customize_domain: {}
  customize_glob: {}
  
# Enables the frontend
frontend:
  themes:
    darkblue:
      primary-color: "#396FB6"
      light-primary-color: "#77a0d4"
      dark-primary-color: "#3539ce"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#3c4348"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--sidebar-text_-_background)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  base_url: !secret base_url

panel_iframe:
# Hass Configurator Panel
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret hassconfig_url

panel_custom: 
# Floorplan Panel
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
  
# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Add Configuration Panel
config:

# View all events in a logbook
logbook: !include includes/logbook.yaml

# Track the sun
sun:

# Text to speech
tts:
  platform: google  
  
# Media Player
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    
# Camera (Synology)
camera:
  - platform: synology
    url: !secret synologycam_url
    username: !secret synologycam_username
    password: !secret synologycam_password
    verify_ssl: False
    timeout: 15
#  - platform: onvif
#    name: front_door
#    host: !secret sensor_onvif_host1
#    username: !secret sensor_onvif_username
#    password: !secret sensor_onvif_password
#    port: !secret sensor_onvif_port
#  - platform: onvif
#    name: back_deck
#    host: !secret sensor_onvif_host2
#    username: !secret sensor_onvif_username
#    password: !secret sensor_onvif_password
#    port: !secret sensor_onvif_port
    
# Microsoft Face - Testing
#microsoft_face:
#  api_key: !secret microsoftface_api

# IFTTT Key
ifttt:
  key: !secret ifttt_api

# iOS App
ios:

# Device Tracking
# MQTT (Local Broker)     
mqtt:
  broker: !secret local_mqtt_broker
  port: !secret local_mqtt_port
  username: !secret local_mqtt_username
  password: !secret local_mqtt_password
  
#  broker: !secret cloud_mqtt_broker
#  port: !secret cloud_mqtt_port
#  username: !secret cloud_mqtt_username
#  password: !secret cloud_mqtt_password

  
#   Owntracks
device_tracker:
#   Owntracks
  - platform: owntracks
#   Router Based Device Tracking
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    exclude: 
     - 192.168.1.105
     - 192.168.1.100
     
#ZWave Devices
zwave:
  usb_path: /dev/ttyACM0
#  polling_interval: 60000
#  autoheal: true

#   Notifications via HTML5
notify:
  - platform: html5
    gcm_api_key: !secret html5_gcm_api
    gcm_sender_id: !secret html5_gcm_sender
    
# Google Assistant Emulated Hue
emulated_hue:
    host_ip: !secret hassbian_ip
#    Google Assistant only Supports Port 80 although it cannot be used due to docker setup.
    listen_port: 80
    expose_by_default: true
    exposed_domains:
      - light
      - switch
# Logitech Harmony Living Room
remote:
  - platform: harmony
    name: !secret harmony_name
    host: !secret harmony_ip

############
# Switches
############
switch 1:
  - platform: broadlink
    host: !secret broadlink_sw1_ip
    mac: '34:EA:34:F5:E4:AC'
    type: spmini2
    friendly_name: 'Living Room Lamp'
switch 2:
  - platform: broadlink
    host: !secret broadlink_sw2_ip
    mac: '34:EA:34:F5:E4:B0'
    type: spmini2
    friendly_name: 'Bed Rachel Lamp'
switch 3:
  - platform: broadlink
    host: !secret broadlink_sw3_ip
    mac: '34:EA:34:F5:E1:18'
    type: spmini2
    friendly_name: 'Bed Trent Lamp'
switch 4:
  - platform: broadlink
    host: !secret broadlink_sw4_ip
    mac: '34:EA:34:F5:E4:F7'
    type: spmini2
    friendly_name: 'Outside Heater'

############
# Additional Zones
############
zone:
  name: !secret zone_name
  latitude: !secret zone_latitude
  longitude: !secret zone_longitude
  icon: mdi:server-network
  radius: 200

zone 2:
  name: !secret zone2_name
  latitude: !secret zone2_latitude
  longitude: !secret zone2_longitude
  icon: mdi:hospital-building
  radius: 200

############
# Includes
############

# Single Files

automation: !include automations.yaml
#apiai: !include includes/apiai.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_slider: !include includes/input_slider.yaml
light: !include includes/light.yaml
weblink: !include includes/weblink.yaml
binary_sensor: !include includes/binary_sensor.yaml
group: !include includes/group.yaml
sensor: !include includes/sensor.yaml
script: !include includes/script.yaml
#image_processing: !include includes/image_processing.yaml


# Merge List

# Non Editor Automations
automation old: !include_dir_merge_list includes/automation