homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
  # Include Packages
  packages: !include_dir_named packages

# Customizations
  customize: !include includes/customize.yaml
  customize_domain: {}
  customize_glob: {}

# Enables the frontend
frontend:
  themes:
    darkblue:
      primary-color: "#396FB6"
      light-primary-color: "#77a0d4"
      dark-primary-color: "#3539ce"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#3c4348"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--text-primary-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  base_url: !secret base_url

panel_iframe:
# Hass Configurator Panel
  configurator:
    title: IDE
    icon: mdi:wrench
    url: !secret ide_url
  terminal:
    title: Terminal
    icon: mdi:console-line
    url: !secret terminal_url

panel_custom:
# Floorplan Panel
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
  - netgear_router

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Add Configuration Panel
config:

# View all events in a logbook
logbook: !include includes/logbook.yaml

# Track the sun
sun:

# Text to speech
tts:

- platform: amazon_polly
  aws_access_key_id: !secret aws_access_key_ID
  aws_secret_access_key: !secret aws_secret_access_key
  text_type: ssml
  voice: Joanna

# Purge Database Interval
recorder:
  purge_interval: 2
  purge_keep_days: 14

# Media Player
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

# Camera (Synology)
camera:
  - platform: synology
    url: !secret synologycam_url
    username: !secret synologycam_username
    password: !secret synologycam_password
    verify_ssl: False
    timeout: 15
#  - platform: onvif
#    name: front_door
#    host: !secret sensor_onvif_host1
#    username: !secret sensor_onvif_username
#    password: !secret sensor_onvif_password
#    port: !secret sensor_onvif_port
#  - platform: onvif
#    name: back_deck
#    host: !secret sensor_onvif_host2
#    username: !secret sensor_onvif_username
#    password: !secret sensor_onvif_password
#    port: !secret sensor_onvif_port

# Microsoft Face - Testing
#microsoft_face:
#  api_key: !secret microsoftface_api

# IFTTT Key
ifttt:
  key: !secret ifttt_api

# iOS App
ios:

# Device Tracking
# MQTT (Local Broker)
mqtt:
  broker: !secret local_mqtt_broker
  port: !secret local_mqtt_port
  username: !secret local_mqtt_username
  password: !secret local_mqtt_password

#  broker: !secret cloud_mqtt_broker
#  port: !secret cloud_mqtt_port
#  username: !secret cloud_mqtt_username
#  password: !secret cloud_mqtt_password

# MQTT Control Panel
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"
    code: !secret alarm_code

#   Owntracks
device_tracker:
#   Owntracks
  - platform: owntracks
#   Router Based Device Tracking
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    exclude:
     - 192.168.1.105
     - 192.168.1.100

#ZWave Devices
zwave:
  usb_path: /dev/ttyACM0
#  polling_interval: 60000
#  autoheal: true

# Logitech Harmony Living Room
remote:
  - platform: harmony
    name: !secret harmony_name
    host: !secret harmony_ip
xiaomi_aqara:
  gateways:
   - mac:
     key: !secret xiaomikey

############
# Additional Zones
############
zone:
  name: !secret zone_name
  latitude: !secret zone_latitude
  longitude: !secret zone_longitude
  icon: mdi:server-network
  radius: 250

zone 2:
  name: !secret zone2_name
  latitude: !secret zone2_latitude
  longitude: !secret zone2_longitude
  icon: mdi:hospital-building
  radius: 250

zone 3:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  icon: mdi:home
  radius: 150

############
# Includes
############

# Single Files

#automation: !include automations.yaml
#dialogflow: !include includes/dialogflow.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
light: !include includes/light.yaml
notify: !include includes/notify.yaml
weblink: !include includes/weblink.yaml
binary_sensor: !include includes/binary_sensor.yaml
group: !include includes/group.yaml
google_assistant: !include includes/google_assistant.yaml
sensor: !include includes/sensor.yaml
scene: !include includes/scene.yaml
script: !include includes/script.yaml
switch: !include includes/switch.yaml
#image_processing: !include includes/image_processing.yaml


# Merge List

# Non Editor Automations
automation: !include_dir_merge_list includes/automation
