############################################################
#
# Binary Sensor
#
############################################################

############################################################
#
# Fibaro Multi Sensor
#
############################################################

- platform: template
  sensors:
    motion:
      value_template: '{{ is_state("sensor.fibaro_system_fgms001zw5_motion_sensor_burglar", "8") }}'
      device_class: motion
    tampering:
      value_template: '{{ is_state("sensor.fibaro_system_fgms001zw5_motion_sensor_burglar", "3") }}'

############################################################
#
# Bayesian Sensor
#
############################################################
      
- platform: bayesian
  prior: 0.75
  name: 'Trent Home'
  probability_threshold: 0.95
  observations:
    - entity_id: 'device_tracker.google_maps_109209758211303121867'
      prob_given_true: 1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.1867b0aa918f'
      prob_given_true: 1
      platform: 'state'
      to_state: 'home'