############################################################
#
# Binary Sensor
#
############################################################

############################################################
#
# Fibaro Multi Sensor
#
############################################################

- platform: template
  sensors:
    motion:
      value_template: '{{ is_state("sensor.fibaro_system_fgms001zw5_motion_sensor_burglar", "8") }}'
      device_class: motion
    tampering:
      value_template: '{{ is_state("sensor.fibaro_system_fgms001zw5_motion_sensor_burglar", "3") }}'