############################################################
#
# Home Assistant Lights
#
############################################################

# MILIGHT LED MQTT
# Commands:  milight/commands/:device_id/:device_type/:group_id
# Updates: milight/commands/:device_id/:device_type/:group_id
- platform: mqtt_json
  name: "Entryway"
  command_topic: milight/commands/0x11/rgb_cct/1
  state_topic: milight/states/0x11/rgb_cct/1
  color_temp: true
  rgb: true
  brightness: true
  effect: true

- platform: mqtt_json
  name: "Entry"
  command_topic: milight/commands/0x11/rgb_cct/2
  state_topic: milight/states/0x11/rgb_cct/2
  color_temp: true
  rgb: true
  brightness: true
  effect: true

- platform: mqtt_json
  name: "Projector Room"
  command_topic: milight/commands/0x11/rgb_cct/3
  state_topic: milight/states/0x11/rgb_cct/3
  color_temp: true
  rgb: true
  brightness: true
  effect: true

- platform: mqtt_json
  name: "Living Room"
  command_topic: milight/commands/0x12/rgb_cct/1
  state_topic: milight/states/0x12/rgb_cct/1
  color_temp: true
  rgb: true
  brightness: true
  effect: true


############
# Yeelight
############
- platform: yeelight
  devices:
    192.168.1.85:
      name: Study Desk Lamp
      transition: 1000
    192.168.1.58:
      name: Trent Bedside
    192.168.1.50:
      name: Rachel Bedside
