############################################################
#
# Home Assistant Lights
#
############################################################

# MILIGHT LED MQTT
# Commands:  milight/commands/:device_id/:device_type/:group_id
# Updates: milight/commands/:device_id/:device_type/:group_id
- platform: mqtt_json
  name: "Entryway"
  command_topic: milight/commands/0x11/rgb_cct/1
  state_topic: milight/states/0x11/rgb_cct/1
  color_temp: true
  rgb: true
  brightness: true
  effect: true

- platform: mqtt_json
  name: "Entry"
  command_topic: milight/commands/0x11/rgb_cct/2
  state_topic: milight/states/0x11/rgb_cct/2
  color_temp: true
  rgb: true
  brightness: true
  effect: true

############
# Yeelight
############
- platform: yeelight
  devices:
    !secret study_desk_lamp_light_ip:
      name: Study Desk Lamp
      transition: 1000
    !secret trent_bedside_light_ip:
      name: Trent Bedside
    !secret rachel_bedside_light_ip:
      name: Rachel Bedside
