############################################################
#
# Sensor
#
############################################################

# Uptime Sensor
- platform: uptime

# Current Time and Date
- platform: time_date
  display_options:
    - 'time'
    - 'date'

# Speedtest
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 12
  monitored_conditions:
    - ping
    - download
    - upload
# NZBGet Monitoring
- platform: nzbget
  host: !secret nzbget_ipaddress
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - download_rate
    - download_paused
# Synology
- platform: synologydsm
  host: !secret sensor_synology_host
  username: !secret sensor_synology_username
  password: !secret sensor_synology_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - disk_status
    - volume_status
    - volume_percentage_used
    - volume_disk_temp_max
# Device Tracking + Activity Templates
- platform: template
  sensors:
    xboxone:
      friendly_name: 'Xbox One'
      value_template: "{{ 'Online' if is_state('device_tracker.281878ebb599', 'home') else 'Offline' }}"
    ps4:
      friendly_name: 'Playstation 4'
      value_template: "{{ 'Online' if is_state('device_tracker.ac899510c96d', 'home') else 'Offline' }}"
    livingroomgooglehome:
      friendly_name: 'Living Room Google Home'
      value_template: "{{ 'Online' if is_state('device_tracker.f4f5d8dc6f8e', 'home') else 'Offline' }}"
    livingroomchromecast:
      friendly_name: 'Living Room Chromecast'
      value_template: "{{ 'Online' if is_state('device_tracker.a477337ee656', 'home') else 'Offline' }}"
    bedroomchromecast:
      friendly_name: 'Bed Room Chromecast'
      value_template: "{{ 'Online' if is_state('device_tracker.80d21d2c642a', 'home') else 'Offline' }}"
    outsidechromecast:
      friendly_name: 'Outside Chromecast Audio'
      value_template: "{{ 'Online' if is_state('device_tracker.546009dca412', 'home') else 'Offline' }}"
    livingroomtv:
      friendly_name: 'Living Room TV'
      value_template: "{{ 'Online' if is_state('device_tracker.f8042e789976', 'home') else 'Offline' }}"
# Translate UPS Status / Runtime
    ups_status:
      friendly_name: 'UPS Status'
      value_template: >-
        {% if is_state('sensor.ups_status_data', 'OL CHRG') %}
          On line Charging
        {% elif is_state('sensor.ups_status_data', 'OB DISCHRG') %}
          On Battery
        {% elif 'LB' in states.sensor.ups_status_data.state %}
           Low battery
        {% elif 'OL' in states.sensor.ups_status_data.state %}
           On line
        {% elif 'SD' in states.sensor.ups_status_data.state %}
          Shutdown load
        {% elif 'CP' in states.sensor.ups_status_data.state %}
          Cable power
        {% elif 'CTS' in states.sensor.ups_status_data.state %}
          Clear to Send
        {% elif 'RTS' in states.sensor.ups_status_data.state %}
          Ready to Send
        {% elif 'DCD' in states.sensor.ups_status_data.state %}
          Data Carrier Detect
        {% elif 'RNG' in states.sensor.ups_status_data.state %}
          Ring indicate
        {% elif 'DTR' in states.sensor.ups_status_data.state %}
          Data Terminal Ready
        {% elif 'ST' in states.sensor.ups_status_data.state %}
          Send Break
        {% endif %}
    ups_battery_runtime_mins:
      friendly_name: 'UPS Battery Runtime'
      unit_of_measurement: 'minutes'
      value_template: "{{ states('sensor.ups_battery_runtime')|float / 60 |round(2)}}" 

# Synology UPS Data
- platform: nut
  name: UPS
  host: !secret sensor_synology_host
  port: 3493
  alias: UPS
  resources:
    - ups.status
    - ups.load
    - ups.realpower.nominal
    - input.voltage
    - battery.runtime
    - battery.charge
