############################################################
#
# Home Assistant Switch
#
############################################################

# Broadlink AC Switches
- platform: broadlink
  host: !secret broadlink_sw1_ip
  mac: '34:EA:34:F5:E4:AC'
  type: spmini2
  friendly_name: 'Living Room Lamp'
- platform: broadlink
  host: !secret broadlink_sw2_ip
  mac: '34:EA:34:F5:E4:B0'
  type: spmini2
  friendly_name: 'Bed Rachel Lamp'
- platform: broadlink
  host: !secret broadlink_sw3_ip
  mac: '34:EA:34:F5:E1:18'
  type: spmini2
  friendly_name: 'Bed Trent Lamp'
- platform: broadlink
  host: !secret broadlink_sw4_ip
  mac: '34:EA:34:F5:E4:F7'
  type: spmini2
  friendly_name: 'Outside Heater'

# Switch Templates for Google Assistant Voice Control
- platform: template
  switches:
    air_conditioner:
      value_template: "{{ is_state('input_select.ac_operation_mode', 'COOL') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.start_air_conditioner
      turn_off:
        service: script.turn_on
        entity_id: script.stop_air_conditioner
