###############################################################################
#   @author         :   Trent Stanton
#   @date           :   1/10/2018
#   @package        :   Battery Levels
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:
    sensor.back_door_sensor_battery:
      device_class: battery
    sensor.front_door_sensor_battery:
      device_class: battery
    sensor.bedroom_window_sensor_battery:
      device_class: battery
    sensor.projector_room_window_sensor_battery:
      device_class: battery
    sensor.living_room_window_1_sensor_battery:
      device_class: battery
    sensor.living_room_window_2_sensor_battery:
      device_class: battery
    sensor.living_room_window_3_sensor_battery:
      device_class: battery
    sensor.dining_room_window_1_sensor_battery:
      device_class: battery
    sensor.dining_room_window_2_sensor_battery:
      device_class: battery
    sensor.washing_machine_sensor_battery:
      device_class: battery
    sensor.hallway_sensor_battery:
      device_class: battery
    sensor.battery_spareswitch_sensor:
      device_class: battery
    sensor.battery_bedroomswitch_sensor:
      device_class: battery
    sensor.battery_entryswitch_sensor:
      device_class: battery
    sensor.battery_bedroomtemp_sensor:
      device_class: battery
    sensor.battery_livingroommulti_sensor:
      device_class: battery
    sensor.battery_smartlock:
      device_class: battery
    sensor.battery_trentbedsideswitch_sensor:
      device_class: battery
    sensor.battery_rachelbedsideswitch_sensor:
      device_class: battery

group:
  Battery Levels:
    control: hidden
    entities:
      - sensor.back_door_sensor_battery
      - sensor.front_door_sensor_battery
      - sensor.bedroom_window_sensor_battery
      - sensor.projector_room_window_sensor_battery
      - sensor.living_room_window_1_sensor_battery
      - sensor.living_room_window_2_sensor_battery
      - sensor.living_room_window_3_sensor_battery
      - sensor.dining_room_window_1_sensor_battery
      - sensor.dining_room_window_2_sensor_battery
      - sensor.washing_machine_sensor_battery
      - sensor.hallway_sensor_battery
      - sensor.battery_spareswitch_sensor
      - sensor.battery_trentbedsideswitch_sensor
      - sensor.battery_rachelbedsideswitch_sensor
      - sensor.battery_entryswitch_sensor
      - sensor.battery_bedroomtemp_sensor
      - sensor.battery_livingroommulti_sensor
      - sensor.battery_smartlock

sensor:
  - platform: mqtt
    name: "Back Door Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d000186f0ec"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Front Door Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d00019f3211"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Bedroom Window Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d0001d7acfc"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Projector Room Window Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d0001e037b3"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Living Room Window 1 Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d0001a4a872"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Living Room Window 2 Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d00019fbe38"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Living Room Window 3 Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d0001e037dc"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Dining Room Window 1 Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d0001e0343b"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Dining Room Window 2 Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d0001d63977"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Washing Machine Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d00019f886a"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: mqtt
    name: "Hallway Sensor Battery"
    state_topic: "zigbee2mqtt/0x00158d000165627b"
    unit_of_measurement: '%'
    value_template: "{{ value_json.battery }}"
  - platform: template
    sensors:
      battery_spareswitch_sensor:
        entity_id:
          - sensor.switch_spare
        value_template: '{% if states.sensor.switch_spare is not none %}
          {{ states.sensor.switch_spare.attributes.battery }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Spare Switch Sensor Battery'
      battery_trentbedsideswitch_sensor:
        entity_id:
          - sensor.switch_trent_bedside
        value_template: '{% if states.sensor.switch_trent_bedside is not none %}
          {{ states.sensor.switch_trent_bedside.attributes.battery }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Trent Bedside Switch Sensor Battery'
      battery_rachelbedsideswitch_sensor:
        entity_id:
          - sensor.switch_trent_bedside
        value_template: '{% if states.sensor.switch_trent_bedside is not none %}
          {{ states.sensor.switch_trent_bedside.attributes.battery }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Rachel Bedside Switch Sensor Battery'
      battery_entryswitch_sensor:
        entity_id:
          - sensor.wall_switch_entryway
        value_template: '{% if states.sensor.wall_switch_entryway is not none %}
          {{ states.sensor.wall_switch_entryway.attributes.battery }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Entryway Switch Sensor Battery'
      battery_bedroomtemp_sensor:
        entity_id:
          - sensor.temperature_bedroom
        value_template: '{% if states.sensor.temperature_bedroom is not none %}
          {{ states.sensor.temperature_bedroom.attributes.battery }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Bedroom Temp Sensor Battery'
      battery_livingroommulti_sensor:
        entity_id:
          - zwave.fibaro_system_fgms001zw5_motion_sensor
        value_template: '{% if states.zwave.fibaro_system_fgms001zw5_motion_sensor is not none %}
          {{ states.zwave.fibaro_system_fgms001zw5_motion_sensor.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Living Room Multi Sensor Battery'
      battery_smartlock:
        entity_id:
          - zwave.kas600_zwave_lock
        value_template: '{% if states.zwave.kas600_zwave_lock is not none %}
          {{ states.zwave.kas600_zwave_lock.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Smart Lock Battery'

# Need to add: Unnamed Switches and Motion Sensors