###############################################################################
#   @author         :   Trent Stanton
#   @date           :   27/02/2019
#   @package        :   Harmony Air Conditioner Control
#   @description    :   Control of AC Split System using Harmony Hub
#   @url            :   https://community.home-assistant.io/t/ac-split-system-integration-via-harmony-remote/21248
###############################################################################

group:
  airconditioner:
    name: AC Split System
    control: hidden
    entities:
      - input_select.ac_operation_mode
      - input_select.ac_fan_mode
      - input_select.ac_swing_mode
      - input_number.ac_target_temp
      - sensor.ac_target
      - sensor.fibaro_motion_sensor_temperature
  ac_scheduler:
    name: AC Scheduler
    control: hidden
    entities:
      - input_boolean.ac_on_schedule_active
      - input_text.ac_on_schedule
      - input_boolean.ac_off_schedule_active
      - input_text.ac_off_schedule

input_boolean:
  ac_on_schedule_active:
    name: Activate AC On schedule
    initial: off
    icon: mdi:calendar
  ac_off_schedule_active:
    name: Activate AC Off schedule
    initial: off
    icon: mdi:calendar

input_number:
  ac_target_temp:
    name: Set Target Temp
    min: 18
    max: 22
    step: 1
    initial: 21
    mode: slider

input_datetime:
  ac_on_schedule:
    name: AC on schedule
    has_date: false
    has_time: true
    initial: '17:00'
  ac_off_schedule:
    name: AC off schedule
    has_date: false
    has_time: true
    initial: '23:30'

input_select:
  ac_operation_mode:
    name: Operating Mode
    options:
      - COOL
      - FAN
      - Power Off
    initial: Power Off
    icon: mdi:settings
  ac_fan_mode:
    name: Fan Mode
    options:
      - AUTO
      - LOW
      - MED
      - HIGH
    initial: AUTO
    icon: mdi:fan
  ac_swing_mode:
    name: Swing Mode
    options:
     - TOP
     - SWING
    initial: TOP
    icon: mdi:arrow-expand

sensor:
  - platform: template
    sensors:
      ac_setting_cool:
        entity_id:
          - input_number.ac_target_temp
          - input_select.ac_fan_mode
          - input_select.ac_swing_mode
        friendly_name: 'Current AC Cool Setting'
        value_template: '{{ states.input_number.ac_target_temp.state | int }}-{{ states.input_select.ac_fan_mode.state }}-{{ states.input_select.ac_swing_mode.state }}'
      ac_setting_fan:
        entity_id:
          - input_select.ac_fan_mode
          - input_select.ac_swing_mode
        friendly_name: 'Current AC Fan Setting'
        value_template: 'FAN-{{ states.input_select.ac_fan_mode.state }}-{{ states.input_select.ac_swing_mode.state }}'
      ac_target:
        entity_id:
          - input_number.ac_target_temp
        friendly_name: 'Target Temperature'
        value_template: '{{ states.input_number.ac_target_temp.state | int }}'
        unit_of_measurement: '°C'
###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: AC Start Cool
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.ac_operation_mode
    - platform: state
      entity_id: input_select.ac_fan_mode
    - platform: state
      entity_id: input_select.ac_swing_mode
    - platform: state
      entity_id: input_number.ac_target_temp
    condition:
    - condition: state
      entity_id: input_select.ac_operation_mode
      state: 'COOL'
    action:
    - service: remote.send_command
      entity_id: remote.living_room
      data_template:
        device: "44392204"
        command: "{{ states.sensor.ac_setting_cool.state }}"

  - alias: AC Start Fan
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.ac_operation_mode
    - platform: state
      entity_id: input_select.ac_fan_mode
    - platform: state
      entity_id: input_select.ac_swing_mode
    condition:
    - condition: state
      entity_id: input_select.ac_operation_mode
      state: 'FAN'
    action:
    - service: remote.send_command
      entity_id: remote.living_room
      data_template:
        device: "44392204"
        command: "{{ states.sensor.ac_setting_fan.state }}"

  - alias: AC Stop
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.ac_operation_mode
      to: 'Power Off'
    action:
    - service: remote.send_command
      entity_id: remote.living_room
      data_template:
        device: "44392204"
        command: "PowerOff"  

  - alias: Turn On AC on schedule
    trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.ac_on_schedule.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
    - condition: state
      entity_id: input_boolean.ac_on_schedule_active
      state: 'on'
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.ac_operation_mode
        option: COOL
    - service: input_boolean.turn_off
      entity_id:
      - input_boolean.ac_on_schedule_active

  - alias: Turn Off AC on schedule
    trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.ac_off_schedule.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
    - condition: state
      entity_id: input_boolean.ac_off_schedule_active
      state: 'on'
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.ac_operation_mode
        option: Power Off
    - service: input_boolean.turn_off
      entity_id:
      - input_boolean.ac_off_schedule_active