############################################################
#
# Home Assistant Last Message Package
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
############################################################

homeassistant:
  customize:
    input_boolean.lastmsg:
      friendly_name: 'Repeat Message'
      icon: mdi:repeat-once
#-------------------------------------------
input_boolean:
  lastmsg:
    name: Last Message
    initial: off
#-------------------------------------------
sensor:
  - platform: mqtt
    state_topic: "broadcast/lastmsg"
    name: "Last Message"
##############################################################################
###  Automations -
##############################################################################

automation:
  - alias: 'Repeat Last Message'

    trigger:
      - platform: state
        entity_id: input_boolean.lastmsg
        to: 'on'

    action:
      - service: notify.google_assistant_broadcast
        data_template:
          message: '{{states.sensor.last_message.state}}'
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.lastmsg
