###############################################################################
#   @author         :   Trent Stanton
#   @date           :   1/09/2018
#   @package        :   Media Players
#   @description    :   Display / Hide Media Players from the Home Assistant Default View when not being used.
#   @url            :   
#   Some configurations not needed in Lovelace
###############################################################################
homeassistant:
  customize:
    media_player.living_room_home:
      friendly_name: Living Room Home
    media_player.tv_ua55ju6400:
      friendly_name: Living Room TV
    media_player.living_room:
      friendly_name: Living Room Chromecast
    media_player.outside:
      friendly_name: Outside Chromecast Audio
    media_player.bed_room:
      friendly_name: Bed Room Chromecast

wake_on_lan:

media_player:
  - platform: plex
  - platform: webostv
    host: !secret webostv_host
    name: Living Room TV
    timeout: 5
    customize:
      sources:
        - Live TV
        - Plex
        - PS4
        - Xbox One
        - Netflix
        - YouTube
        - 9Now
        - ABC iview
        - SBS on Demand
        - LG Content Store
        - Web Browser
        - TV Guide
        - TV Scheduler
        - HDMI 2
        - HDMI 4
    turn_on_action:
        service: wake_on_lan.send_magic_packet
        data:
          mac: !secret webostv_mac
sensor:
  - platform: template
    sensors:
      living_room_tv_source:
        entity_id:
          - media_player.living_room_tv
        value_template: "{{ states.media_player.living_room_tv.attributes.source }}"

group:
  media_living_room_home:
    name: Media Living Room Home
    entities:
      - media_player.living_room_home
  media_living_room_tv:
    name: Media Living TV
    entities:
      - media_player.living_room_tv
  media_living_room:
    name: Media Living Room
    entities:
      - media_player.living_room
  media_bed_room:
    name: Media Bed Room
    entities:
      - media_player.bed_room
  media_bedroom_speaker:
    name: Media Bed Room Speaker
    entities:
      - media_player.bedroom_speaker
  media_outside:
    name: Media Outside
    entities:
      - media_player.outside
script:
  turn_on_plex:
    alias: "Start Plex"
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.living_room_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.living_room_tv
          source: 'Plex'
  turn_on_xboxone:
    alias: "Start Xbox One"
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.living_room_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.living_room_tv
          source: 'Xbox One'
  turn_on_ps4:
    alias: "Start PS4"
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.living_room_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.living_room_tv
          source: 'PS4'

###############################################################################
#                               Automations
###############################################################################
automation:

## Media Player Living Room Home
# Hide Media Player
  - alias: 'Hide media_player.living_room_home while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.living_room_home
      to: 'idle'
    - platform: state
      entity_id: media_player.living_room_home
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_living_room_home
      data:
        visible: False
  # Show Media Player

  - alias: 'Show media_player.office while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.living_room_home
      to: 'playing'
    - platform: state
      entity_id: media_player.living_room_home
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_living_room_home
      data:
        visible: True
  
  ## Media Player Living Room TV
  # Hide Media Player

  - alias: 'Hide media_player.tv_ua55ju6400 while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.tv_ua55ju6400
      to: 'idle'
    - platform: state
      entity_id: media_player.tv_ua55ju6400
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_living_room_tv
      data:
        visible: False
  # Show Media Player

  - alias: 'Show media_player.tv_ua55ju6400 while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.tv_ua55ju6400
      to: 'playing'
    - platform: state
      entity_id: media_player.tv_ua55ju6400
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_living_room_tv
      data:
        visible: True

## Media Player Living Room
# Hide Media Player
  - alias: 'Hide media_player.living_room while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.living_room
      to: 'idle'
    - platform: state
      entity_id: media_player.living_room
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_living_room
      data:
        visible: False
# Show Media Player
  
  - alias: 'Show media_player.living_room while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
    - platform: state
      entity_id: media_player.living_room
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_living_room
      data:
        visible: True

## Media Player Bed Room
# Hide Media Player
  - alias: 'Hide media_player.bed_room while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.bed_room
      to: 'idle'
    - platform: state
      entity_id: media_player.bed_room
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_bed_room
      data:
        visible: False
# Show Media Player

  - alias: 'Show media_player.bed_room while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.bed_room
      to: 'playing'
    - platform: state
      entity_id: media_player.bed_room
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_bed_room
      data:
        visible: True

## Media Player Bed Room Speaker
# Hide Media Player

  - alias: 'Hide media_player.bedroom_speaker while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.bedroom_speaker
      to: 'idle'
    - platform: state
      entity_id: media_player.bedroom_speaker
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_bedroom_speaker
      data:
        visible: False
# Show Media Player

  - alias: 'Show media_player.bedroom_speaker while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.bedroom_speaker
      to: 'playing'
    - platform: state
      entity_id: media_player.bedroom_speaker
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_bedroom_speaker
      data:
        visible: True

## Media Player Outside
# Hide Media Player

  - alias: 'Hide media_player.outside while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.outside
      to: 'idle'
    - platform: state
      entity_id: media_player.outside
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_outside
      data:
        visible: False
# Show Media Player

  - alias: 'Show media_player.outside while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.outside
      to: 'playing'
    - platform: state
      entity_id: media_player.outside
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_outside
      data:
        visible: True