###############################################################################
#   @author         :   Trent Stanton
#   @date           :   7/04/2019
#   @package        :   Media Players
#   @description    :   Media Player Setup and Automations
#   @url            :   
#   
###############################################################################
homeassistant:
  customize:
    media_player.living_room_home:
      friendly_name: Living Room Home
    media_player.tv_ua55ju6400:
      friendly_name: Living Room TV
    media_player.living_room:
      friendly_name: Living Room Chromecast
    media_player.outside:
      friendly_name: Outside Chromecast Audio
    media_player.bed_room:
      friendly_name: Bed Room Chromecast
    input_boolean.disable_turn_off_tv_away:
      icon: mdi:television

input_boolean:
  disable_turn_off_tv_away:
    name: Disable Turn Off Living Room TV If Away
    initial: off

wake_on_lan:

media_player:
  - platform: plex
  - platform: webostv
    host: !secret webostv_host
    name: Living Room TV
    timeout: 5
    customize:
      sources:
        - Live TV
        - Plex
        - PS4
        - Xbox One
        - Retropie
        - Netflix
        - Amazon Prime Video
        - YouTube
        - 9Now
        - ABC iview
        - SBS on Demand
        - LG Content Store
        - Web Browser
        - TV Guide
        - TV Scheduler
        - HDMI 2
    turn_on_action:
        service: wake_on_lan.send_magic_packet
        data:
          mac: !secret webostv_mac
## Also used in 'downloads.yaml'.
sensor:
  - platform: template
    sensors:
      living_room_tv_source:
        entity_id:
          - media_player.living_room_tv
        value_template: "{{ states.media_player.living_room_tv.attributes.source }}"
        friendly_name: 'Living Room TV Source'
script:
  turn_on_plex:
    alias: "Start Plex"
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.living_room_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.living_room_tv
          source: 'Plex'
  turn_on_xboxone:
    alias: "Start Xbox One"
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.living_room_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.living_room_tv
          source: 'Xbox One'
  turn_on_ps4:
    alias: "Start PS4"
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.living_room_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.living_room_tv
          source: 'PS4'

###############################################################################
#                               Automations
###############################################################################
automation:
# Turn off Living Room TV if away from home.
  - alias: Turn Off Living Room TV If Away
    trigger:
    - platform: state
      entity_id: group.family_presence
      from: 'home'
      to: 'not_home'
      for:
        minutes: 10
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: group.motionsensors
        state: 'off'
        for:
          minutes: 5
      - condition: state
        entity_id: group.family_presence
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.disable_turn_off_tv_away
        state: 'off'
    action:
    - delay: '00:00:30'
    - service: media_player.turn_off
      entity_id: media_player.living_room_tv