###############################################################################
#   @author         :   Trent Stanton
#   @date           :   12/05/2018
#   @package        :   Outside Heater Auto Off
#   @description    :   Outside Heater Auto Power Off - 3 Hours
#   @url            :   
###############################################################################
homeassistant:
  customize:
    input_boolean.disable_auto_off_outside_heater:
      icon: mdi:fire

input_boolean:
  disable_auto_off_outside_heater:
    name: Disable Auto Off Outside Heater
    initial: off
  
timer:
  outside_heater:

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: Start Outside Heater Auto Off Timer
    trigger:
      - platform: state
        entity_id: switch.outside_heater
        to: 'on'
    action: 
      - service: timer.start
        entity_id: timer.outside_heater
        data:
          duration: '03:00:00'

  - alias: Cancel Outside Heater Auto Off Timer
    trigger:
      - platform: state
        entity_id: switch.outside_heater
        to: 'off'
    action: 
      - service: timer.cancel
        entity_id: timer.outside_heater

  - alias: Auto Turn Off Outside Heater
    trigger: 
      - platform: event
        event_type: timer.finished
        event_data: 
          entity_id: timer.outside_heater
    condition:
      - condition: state
        entity_id: input_boolean.disable_auto_off_outside_heater
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.outside_heater