###############################################################################
#   @author         :   Trent Stanton
#   @date           :   27/02/2019
#   @package        :   
#   @description    :   Package Tracking - WIP
#   @url            :   
###############################################################################
sensor:
  - platform: aftership
    api_key: !secret aftership_api_key

###############################################################################
#                               Automations
###############################################################################
# automation:
