###############################################################################
#   @author         :   Trent Stanton
#   @date           :   9/04/2018
#   @package        :   
#   @description    :   Security Sensors
#   @url            :   
###############################################################################
homeassistant:
  customize:
    sensor.door_count:
      friendly_name: Open Door Count
      icon: mdi:door-open
    sensor.window_count:
      friendly_name: Open Window Count
      icon: mdi:window-open
    binary_sensor.door_frontdoor:
      device_class: door
    binary_sensor.door_backdoor:
      device_class: door
    binary_sensor.window_bedroom:
      device_class: window
    binary_sensor.window_projectorroom:
      device_class: window
    binary_sensor.window_livingroom1:
      device_class: window
    binary_sensor.window_livingroom2:
      device_class: window
    binary_sensor.window_livingroom3:
      device_class: window
    binary_sensor.window_diningroom1:
      device_class: window
    binary_sensor.window_diningroom2:
      device_class: window

group:
  doorandwindowsensors:
    name: Door and Window Sensors
    control: hidden
    entities:
      - sensor.door_count
      - sensor.window_count
      - binary_sensor.door_frontdoor
      - binary_sensor.door_backdoor
      - binary_sensor.window_bedroom
      - binary_sensor.window_projectorroom
      - binary_sensor.window_livingroom1
      - binary_sensor.window_livingroom2
      - binary_sensor.window_livingroom3
      - binary_sensor.window_diningroom1
      - binary_sensor.window_diningroom2
sensor:
  - platform: template
    sensors:
      door_count:
        value_template: >-
          {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'door') | list | count | int }}
      window_count:
        value_template: >-
          {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'window') | list | count | int }}