###############################################################################
#   @author         :   Trent Stanton
#   @date           :   1/09/2018
#   @package        :   Yeelight Lights
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:
    light.trent_bedside:
      icon: mdi:lamp
    light.rachel_bedside:
      icon: mdi:lamp
    light.study_desk_lamp:
      icon: mdi:lamp
light:
  - platform: yeelight
    devices:
      !secret study_desk_lamp_light_ip:
        name: Study Desk Lamp
        transition: 1000
      !secret yeelink_light_strip:
        name: Yeelink Light Strip
      !secret trent_bedside_light_ip:
        name: Trent Bedside
      !secret rachel_bedside_light_ip:
        name: Rachel Bedside