###############################################################################
#   @author         :   Trent Stanton
#   @date           :   1/09/2018
#   @package        :   Yeelight Lights
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:
    light.trent_bedside:
      icon: mdi:lamp
    light.rachel_bedside:
      icon: mdi:lamp
    light.study_desk_lamp:
      icon: mdi:lamp

yeelight:
  devices:
    !secret study_desk_lamp_light_ip:
      name: Study Desk Lamp
      transition: 1000
    !secret yeelink_light_strip:
      name: Yeelink Light Strip
    !secret trent_bedside_light_ip:
      model: color1
      name: Trent Bedside
    !secret rachel_bedside_light_ip:
      model: color1
      name: Rachel Bedside

scene:
  - name: Bedroom Default
    entities:
      light.trent_bedside:
        state: true
        xy_color: [0.621, 0.367]
        brightness: 15
      light.rachel_bedside:
        state: true
        xy_color: [0.621, 0.367]
        brightness: 15
  - name: Bedroom Romantic
    entities:
      light.trent_bedside:
        state: true
        xy_color: [0.51, 0.239]
        brightness: 5
      light.rachel_bedside:
        state: true
        xy_color: [0.51, 0.239]
        brightness: 5